title: rolod0x
repository: rolod0x/rolod0x
description: >-
  Your free private onchain address book
lsi: false
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
color_scheme: rolod0x-light
theme: just-the-docs
#theme: minima
#theme: jekyll-theme-hacker
plugins:
  - jekyll-readme-index
readme_index:
  enabled: true
  remove_originals: true
  with_frontmatter: false
optional_front_matter:
  remove_originals: true

include:
  - CONTRIBUTING.md
exclude:
  - bin/
  - .#*

defaults:
  - scope:
      path: ''
    values:
      image: https://rolod0x.io/docs/images/promo/social-1200x630.png
  - scope:
      path: README.md
    values:
      title: Overview
      nav_order: 0
  - scope:
      path: docs/install.md
    values:
      nav_order: 1
  - scope:
      path: docs/user-manual.md
    values:
      nav_order: 2
  - scope:
      path: docs/FAQ.md
    values:
      nav_order: 3
  - scope:
      path: docs/privacy-policy.md
    values:
      nav_order: 4
  - scope:
      path: docs/SECURITY.md
    values:
      nav_order: 5
  - scope:
      path: CONTRIBUTING.md
    values:
      title: Support
      nav_order: 6
  - scope:
      path: docs/dev-guide.md
    values:
      nav_order: 7
