name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: rolod0x.zip
          path: dist/*

      - name: Create zip file
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          RELEASE_NAME="rolod0x-${{github.ref_name}}"
          echo "RELEASE_NAME=$RELEASE_NAME"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

          mv dist $RELEASE_NAME
          zip -r $RELEASE_NAME.zip $RELEASE_NAME/

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "${{env.RELEASE_NAME}}.zip"
          draft: true
          generateReleaseNotes: true

# See also release.yml
